application:
  port: 8000
  api_key: "1234567890"
  public_key: "987654321"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "fish"
s3:
  region: "us-east-2"
  bucket: "local"
  access_key_id: "local"
  secret_access_key: "local_secret"
